version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: audit-postgres
    environment:
      - POSTGRES_DB=audit_db
      - POSTGRES_USER=audit_user
      - POSTGRES_PASSWORD=secure_password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit_user -d audit_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: